before:
  hooks:
    - go mod tidy
builds:
  -
    goos:
      - darwin
      - linux
      - freebsd

    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x

    flags:
      - -trimpath
      - --tags=kqueue

    ldflags:
      - -s -w -X main.version={{.Tag}}

    env:
      - CGO_ENABLED=0

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
